CREATE DATABASE Supermarket

CREATE TABLE Categories (
Id INT IDENTITY(1, 1) PRIMARY KEY,
Name NVARCHAR(30) NOT NULL
)

CREATE TABLE Items (
Id INT IDENTITY(1, 1) PRIMARY KEY,
Name NVARCHAR(30) NOT NULL,
Price DECIMAL(15, 2) NOT NULL,
CategoryId INT NOT NULL REFERENCES Categories(Id)
)

CREATE TABLE Employees (
Id INT IDENTITY(1, 1) PRIMARY KEY,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
Phone CHAR(12) NOT NULL,
Salary DECIMAL(15, 2) NOT NULL
)

CREATE TABLE Orders (
Id INT IDENTITY(1, 1) PRIMARY KEY,
DateTime DATETIME2 NOT NULL,
EmployeeId INT NOT NULL REFERENCES Employees(Id)
)

CREATE TABLE OrderItems (
OrderId INT NOT NULL REFERENCES Orders(Id),
ItemId INT NOT NULL REFERENCES Items(Id),
Quantity INT NOT NULL CHECK(Quantity >= 1)

PRIMARY KEY(OrderId, ItemId)
)

CREATE TABLE Shifts (
Id INT IDENTITY(1, 1) NOT NULL,
EmployeeId INT NOT NULL REFERENCES Employees(Id),
CheckIn DATETIME2 NOT NULL,
CheckOut DATETIME2 NOT NULL

PRIMARY KEY(Id, EmployeeId)
)

ALTER TABLE Shifts 
ADD CONSTRAINT CHK_CheckDates CHECK(CheckIn < CheckOut)